version: "3.0"
services:

  database:
    container_name: srra_mongo
    image: mongo
    tty: true
    ports: 
      - 27020:27017

networks:
  default:
    external:
      name: rede_dev


#docker network create --driver bridge --subnet 10.254.0.0/16 rede_dev
